version: '3.8'

services:
  web:
    build: .
    command: gunicorn git_ctf_website.wsgi:application --bind 0.0.0.0:8000 --pythonpath /usr/src/git-ctf-website/git_ctf_website
    volumes:
      - static_volume:/usr/src/git-ctf-website/static
    expose:
      - 8000
    env_file:
      - ./.django.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.env

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/git-ctf-website/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:


